name: Greet User
#on: push
on: workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello, User! Welcome to the repository."
      - name: Show current date and time
        run: date